# when tagging, use this dictionary
possible_tags = ['CONDITION',
                 'BRANCH',
                 'MEDICALDOCTOR',
                 'MENTALHEALTH',
                 'DISEASE',
                 'ANATOMY',
                 'DRUG',
                 'PERSON',
                 'PROCEDURE',
                 'MEDICALTOOL',
                 'INSURANCE',
                 'LOC',
                 'DISTANCE',
                 'POSITION',
                 'SIZE',
                 'SYMPTOM',
                 'NEGATION',
                 'JARGON'
                 ]
